services:
  archypix-app-db:
    image: mysql:8.4
    container_name: archypix-app-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: archypix
      MYSQL_DATABASE: archypix
      MYSQL_USER: archypix
      MYSQL_PASSWORD: archypix
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql

  archypix-app-minio:
    image: minio/minio:latest
    container_name: archypix-app-minio
    environment:
      MINIO_ROOT_USER: archypix
      MINIO_ROOT_PASSWORD: 15hm434Yxzmvtm851VjnlslFHjVFqBkrz72tc2EZOM4hfZBp
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO console
    volumes:
      - ./data/minio:/data
    command: ["server", "/data", "--address", ":9000", "--console-address", ":9001"]

  archypix-app-back:
    build: .
    image: archypix-app-back
    container_name: archypix-app-back
    restart: unless-stopped
    depends_on:
      - archypix-app-db
      - archypix-app-minio
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=mysql://user:password@host:3306/database
      - SMTP_SERVER=$SMTP_SERVER
      - SMTP_SERVER_PORT=$SMTP_SERVER_PORT
      - SMTP_FROM_NAME=$SMTP_FROM_NAME
      - SMTP_USERNAME=$SMTP_USERNAME
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - FRONTEND_HOST=$FRONTEND_HOST
      - BACKEND_HOST=$BACKEND_HOST
