services:
  archypix-app-postgres:
    image: postgres:17
    container_name: archypix-app-postgres
    environment:
      POSTGRES_PASSWORD: archypix
      POSTGRES_DB: archypix
      POSTGRES_USER: archypix
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  archypix-app-minio:
    image: minio/minio:latest
    container_name: archypix-app-minio
    environment:
      MINIO_ROOT_USER: archypix
      MINIO_ROOT_PASSWORD: 15hm434Yxzmvtm851VjnlslFHjVFqBkrz72tc2EZOM4hfZBp
    ports:
      - "9002:9000" # MinIO API
      - "9001:9001" # MinIO console
    volumes:
      - ./data/minio:/data
    command: ["server", "/data", "--address", ":9000", "--console-address", ":9001"]

  archypix-app-back:
    build: .
    image: archypix-app-back
    container_name: archypix-app-back
    depends_on:
      - archypix-app-postgres
      - archypix-app-minio
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgres://archypix:archypix@archypix-app-postgres:5432/archypix
      - AWS_ENDPOINT=http://archypix-app-minio:9000
      - FRONTEND_HOST=$FRONTEND_HOST
      - BACKEND_HOST=$BACKEND_HOST
      - SMTP_SERVER=$SMTP_SERVER
      - SMTP_SERVER_PORT=$SMTP_SERVER_PORT
      - SMTP_FROM_NAME=$SMTP_FROM_NAME
      - SMTP_FROM_ADDRESS=$SMTP_FROM_ADDRESS
      - SMTP_USERNAME=$SMTP_USERNAME
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION
